namespace: sqaaas
resources:
  - namespace.yaml
  - sqaaas-api-dev.yaml
  - sqaaas-api-staging.yaml
secretGenerator:
- name: github-token
  files:
  - .gh_token
- name: jenkins-token
  files:
  - .jk_token
