namespace: sqaaas
resources:
  - namespace.yaml
  - sqaaas-api.yaml
  - sqaaas-web.yaml
secretGenerator:
- name: github-token
  files:
  - .gh_token
- name: jenkins-token
  files:
  - .jk_token
configMapGenerator:
- name: api-config-file
  files:
    - sqaaas.ini
