namespace: sqaaas
resources:
  - namespace.yaml
  - sqaaas-api.yaml
  - sqaaas-web.yaml
  - sqaaas-badgr.yaml
secretGenerator:
- name: github-token
  files:
  - .gh_token
- name: jenkins-token
  files:
  - .jk_token
- name: badgrserver
  files:
  - server.crt
  - server.key
#  type: "kubernetes.io/tls"
- name: mysql
  literals:
  - rootpassword=badgr-mysql-root-pass
  - password=badgr-mysql-pass
configMapGenerator:
- name: api-config-file
  files:
    - sqaaas.ini
- name: badgrserver
  files:
    - settings_local.py
- name: badgrui
  files:
    - nginx.conf
- name: mysql-db-init
  files:
    - badgr.sql